
import __ASTRO_IMAGE_IMPORT_ZpO0xf from "./images/photoshoot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fbehind-the-scenes-with-our-artists.md";
import __ASTRO_IMAGE_IMPORT_ZCbj7o from "./images/band.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcollaboration-in-music-production.md";
import __ASTRO_IMAGE_IMPORT_Z1Bt0DQ from "./images/record.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcreating-a-successful-music-brand.md";
import __ASTRO_IMAGE_IMPORT_Z1uXMgW from "./images/gear.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgear-is-insanely-expensive.md";
import __ASTRO_IMAGE_IMPORT_1WcTwU from "./images/guitarist.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fguitar-solos-are-still-awesome.md";
import __ASTRO_IMAGE_IMPORT_2vt3T4 from "./images/concert.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Flive-music-is-crucial.md";
import __ASTRO_IMAGE_IMPORT_4hNmU from "./images/producer.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-art-of-music-production.md";
import __ASTRO_IMAGE_IMPORT_Fu5sn from "./images/studio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmaking-a-home-studio.md";
import __ASTRO_IMAGE_IMPORT_ZmBqTH from "./images/drums.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftune-your-snare-drum.md";
import __ASTRO_IMAGE_IMPORT_ZnLVay from "./images/speaker.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-importance-of-audio-quality.md";
export default new Map([["./images/photoshoot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fbehind-the-scenes-with-our-artists.md", __ASTRO_IMAGE_IMPORT_ZpO0xf], ["./images/band.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcollaboration-in-music-production.md", __ASTRO_IMAGE_IMPORT_ZCbj7o], ["./images/record.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcreating-a-successful-music-brand.md", __ASTRO_IMAGE_IMPORT_Z1Bt0DQ], ["./images/gear.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgear-is-insanely-expensive.md", __ASTRO_IMAGE_IMPORT_Z1uXMgW], ["./images/guitarist.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fguitar-solos-are-still-awesome.md", __ASTRO_IMAGE_IMPORT_1WcTwU], ["./images/concert.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Flive-music-is-crucial.md", __ASTRO_IMAGE_IMPORT_2vt3T4], ["./images/producer.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-art-of-music-production.md", __ASTRO_IMAGE_IMPORT_4hNmU], ["./images/studio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmaking-a-home-studio.md", __ASTRO_IMAGE_IMPORT_Fu5sn], ["./images/drums.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftune-your-snare-drum.md", __ASTRO_IMAGE_IMPORT_ZmBqTH], ["./images/speaker.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-importance-of-audio-quality.md", __ASTRO_IMAGE_IMPORT_ZnLVay]]);
		